#!/usr/bin/env node
/**
 * figma-check.mjs — drift check between the code contract and the Figma library
 *
 * Reads tokens/component-contract.json (generated by `npm run contract`)
 *       the Figma file over the REST API
 * Exits 1 on drift, 2 on configuration problems, 0 when they agree.
 *
 * Works on the Figma Professional plan. The Variables REST API is Enterprise only,
 * so this cannot read variable names or values. What it can see is structural:
 * which component sets exist, what properties they expose, and whether a node's
 * paint is bound to a variable or hardcoded. Value-level auditing runs through the
 * Plugin API instead (see docs/design-system-pipeline.md).
 *
 * Setup: add to .env.local
 *   FIGMA_TOKEN=figd_...      personal access token, File content scope: Read
 *   FIGMA_FILE_KEY=...        the key from figma.com/design/<key>/<name>
 *
 * Run with: npm run figma:check
 */
import { readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CONTRACT = resolve(root, 'tokens/component-contract.json')

/* --------------------------------------------------------------- env load */

for (const file of ['.env.local', '.env']) {
  const path = resolve(root, file)
  if (!existsSync(path)) continue
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
}

const TOKEN = process.env.FIGMA_TOKEN
const FILE_KEY = process.env.FIGMA_FILE_KEY

const fail = (msg, code = 2) => {
  console.error(`figma:check ${msg}`)
  process.exit(code)
}

if (!TOKEN) fail('needs FIGMA_TOKEN in .env.local (personal access token, File content scope: Read)')
if (!FILE_KEY) fail('needs FIGMA_FILE_KEY in .env.local (from figma.com/design/<key>/<name>)')
if (!existsSync(CONTRACT)) fail('needs tokens/component-contract.json. Run `npm run contract` first.')

/* ------------------------------------------------------------------ fetch */

// A network or auth failure must not exit 1: that is the drift code, and CI would
// report clean-but-unreachable as a design system violation.
// FIGMA_API_BASE exists so the checker can be run against a stub in tests.
const API_BASE = process.env.FIGMA_API_BASE ?? 'https://api.figma.com'

let res
try {
  res = await fetch(`${API_BASE}/v1/files/${FILE_KEY}`, {
    headers: { 'X-Figma-Token': TOKEN },
  })
} catch (err) {
  fail(`could not reach ${API_BASE} (${err.cause?.code ?? err.message}). Check the network, not the design system.`)
}

if (!res.ok) {
  const body = await res.text().catch(() => '')
  const hint =
    res.status === 403 ? ' Check FIGMA_TOKEN has the File content scope set to Read and has not expired.'
    : res.status === 404 ? ' Check FIGMA_FILE_KEY matches the file URL.'
    : ''
  fail(`Figma API returned ${res.status}.${hint} ${body.slice(0, 200)}`)
}

const file = await res.json()

/* ------------------------------------------------------------------ walk */

const componentSets = new Map() // name -> node
const components = new Map()
const unboundPaints = []

/** Figma appends an id to property names: "label#12:34". The code side never sees it. */
const bare = (name) => name.split('#')[0]

const walk = (node, page, insideComponent = false, insideSet = false) => {
  if (node.type === 'COMPONENT_SET') {
    componentSets.set(node.name, { node, page })
    insideComponent = true
    insideSet = true
  }
  if (node.type === 'COMPONENT') {
    // A COMPONENT inside a COMPONENT_SET is one variant ("size=md"), not a component of
    // its own. The set is what the contract names; its children are counted, not matched.
    if (!insideSet) components.set(node.name, { node, page })
    insideComponent = true
  }

  if (insideComponent && Array.isArray(node.fills)) {
    const solid = node.fills.filter((f) => f.type === 'SOLID' && f.visible !== false)
    const bound = node.boundVariables?.fills
    if (solid.length > 0 && !bound) {
      unboundPaints.push(`${page} / ${node.name} (${node.type})`)
    }
  }

  for (const child of node.children ?? []) walk(child, page, insideComponent, insideSet)
}

for (const page of file.document.children ?? []) {
  for (const child of page.children ?? []) walk(child, page.name)
}

/* ------------------------------------------------------------------ diff */

const contract = JSON.parse(readFileSync(CONTRACT, 'utf8'))
const errors = []
const warnings = []

for (const component of contract.components) {
  const expectVariants = component.variantAxes.length > 0
  const found = expectVariants ? componentSets.get(component.name) : (componentSets.get(component.name) ?? components.get(component.name))

  if (!found) {
    errors.push(`${component.name}: in code (${component.storyFile}) but not in the Figma file`)
    continue
  }

  const defs = found.node.componentPropertyDefinitions ?? {}
  const figmaProps = new Map(Object.entries(defs).map(([k, v]) => [bare(k), v]))

  for (const prop of component.props) {
    const spec = prop.figma
    if (spec.figmaType === 'NONE') continue // data prop: content, not a Figma property
    const actual = figmaProps.get(spec.name)

    if (!actual) {
      errors.push(`${component.name}.${spec.name}: expected a ${spec.figmaType} property in Figma, found none`)
      continue
    }
    if (actual.type !== spec.figmaType) {
      errors.push(`${component.name}.${spec.name}: Figma has ${actual.type}, contract says ${spec.figmaType}`)
    }
    if (spec.figmaType === 'VARIANT') {
      const figmaValues = [...(actual.variantOptions ?? [])].sort()
      const codeValues = [...spec.values].sort()
      if (figmaValues.join('|') !== codeValues.join('|')) {
        errors.push(
          `${component.name}.${spec.name}: values differ. Figma [${figmaValues.join(', ')}] vs code [${codeValues.join(', ')}]`,
        )
      }
    }
    // Only assert a default where the code actually declares one. A prop with no
    // default leaves Figma free to carry whatever placeholder reads best.
    if (prop.default !== null && prop.default !== undefined && typeof prop.default !== 'object') {
      if (actual.defaultValue !== prop.default) {
        errors.push(
          `${component.name}.${spec.name}: default is ${JSON.stringify(actual.defaultValue)} in Figma, ` +
            `${JSON.stringify(prop.default)} in code` +
            (spec.figmaType === 'VARIANT'
              ? '. Figma takes the top-left variant as the default, so move that variant leftmost.'
              : ''),
        )
      }
    }

    if (spec.companionBoolean && !figmaProps.has(spec.companionBoolean)) {
      warnings.push(
        `${component.name}.${spec.companionBoolean}: ${spec.name} is optional in code, so Figma needs a boolean to hide it`,
      )
    }
    figmaProps.delete(spec.name)
    if (spec.companionBoolean) figmaProps.delete(spec.companionBoolean)
  }

  for (const extra of figmaProps.keys()) {
    errors.push(`${component.name}.${extra}: property exists in Figma with no matching prop in code`)
  }

  if (expectVariants) {
    const actualCount = found.node.children?.length ?? 0
    if (actualCount !== component.expectedVariantCount) {
      errors.push(
        `${component.name}: ${actualCount} variants in Figma, contract expects ${component.expectedVariantCount}`,
      )
    }
  }
}

const codeNames = new Set(contract.components.map((c) => c.name))
for (const name of [...componentSets.keys(), ...components.keys()]) {
  // Icons (Icon/Search) are swap targets for INSTANCE_SWAP props, not code components.
  if (name.startsWith('Icon/')) continue
  if (!codeNames.has(name)) warnings.push(`${name}: in the Figma file with no component in code`)
}
for (const node of unboundPaints) warnings.push(`${node}: solid fill not bound to a variable`)

/* ---------------------------------------------------------------- report */

console.log(`figma:check ${file.name} (${contract.components.length} components in contract)`)
for (const w of warnings) console.log(`  warn  ${w}`)
for (const e of errors) console.error(`  drift ${e}`)

if (errors.length > 0) {
  console.error(`\n${errors.length} drift${errors.length === 1 ? '' : 's'} between code and Figma.`)
  process.exit(1)
}
console.log(warnings.length > 0 ? `\nNo drift. ${warnings.length} warning(s).` : '\nNo drift.')
